"""Team Panel auth domain value objects — immutable refs.

P2-S14A: QR code, phone verification, JWT token references.
"""
from dataclasses import dataclass
from typing import Optional


@dataclass(frozen=True)
class QRCodeRef:
    """Reference to a QR code login ticket.
    
    Generated by auth service, consumed by scan confirmation.
    """
    id: str  # unique ticket ID
    enterprise_id: str
    qr_data: str  # base64 or URL-encoded QR image data
    scan_url: str  # the URL embedded in QR code
    expires_at: str
    created_at: str
    scanned_by_user_id: Optional[str] = None
    scanned_at: Optional[str] = None
    confirmed_at: Optional[str] = None
    status: str = "pending"  # pending | scanned | confirmed | expired | cancelled

    _VALID_STATUS = frozenset({"pending", "scanned", "confirmed", "expired", "cancelled"})
    _TERMINAL = frozenset({"confirmed", "expired", "cancelled"})

    def is_pending(self) -> bool:
        return self.status == "pending"

    def is_scanned(self) -> bool:
        return self.status == "scanned"

    def is_confirmed(self) -> bool:
        return self.status == "confirmed"


@dataclass(frozen=True)
class PhoneVerificationRef:
    """Reference to a phone verification code.
    
    SMS verification code with rate limiting metadata.
    """
    id: str  # unique verification ID
    phone_number: str  # target phone number
    code_hash: str  # hashed verification code (NOT raw code)
    enterprise_id: str
    expires_at: str
    created_at: str
    verified_at: Optional[str] = None
    attempts: int = 0
    max_attempts: int = 5
    status: str = "pending"  # pending | verified | expired | exceeded

    _VALID_STATUS = frozenset({"pending", "verified", "expired", "exceeded"})

    def is_pending(self) -> bool:
        return self.status == "pending"

    def is_verified(self) -> bool:
        return self.status == "verified"

    def can_attempt(self) -> bool:
        return self.status == "pending" and self.attempts < self.max_attempts


@dataclass(frozen=True)
class JWTTokenRef:
    """Reference to a JWT token pair (access + refresh).
    
    Immutable snapshot of token metadata (not the actual token).
    """
    access_jti: str  # JWT ID for access token
    refresh_jti: str  # JWT ID for refresh token
    enterprise_id: str
    user_id: str
    access_expires_at: str
    refresh_expires_at: str
    issued_at: str
    algorithm: str = "RS256"
    key_id: Optional[str] = None  # JWKS key ID


@dataclass(frozen=True)
class AuthRateLimitKey:
    """Rate limiting key for auth operations.
    
    Composite key for tracking auth attempts per enterprise/user/method.
    """
    enterprise_id: str
    key_type: str  # "user" | "ip" | "phone" | "enterprise"
    key_value: str  # user_id / ip_address / phone_number
    action: str  # "login" | "refresh" | "verify_phone" | "scan_qr"

    def to_cache_key(self) -> str:
        return f"auth_rate:{self.enterprise_id}:{self.key_type}:{self.key_value}:{self.action}"