import AxeBuilder from "@axe-core/playwright";
import { authTest, expect } from "../support/fixtures";
import { seededEmployeeId } from "../support/auth";
import { collectBrowserErrors, expectKeyboardFocusVisible } from "../support/smoke";

async function stabilizeConversationAvatars(page: import("@playwright/test").Page): Promise<void> {
  await page.route("**/api/agent/conversations?*", async (route) => {
    if (route.request().method() !== "GET") {
      await route.continue();
      return;
    }
    const response = await route.fetch();
    const payload = (await response.json()) as { data?: Array<Record<string, unknown>> };
    if (Array.isArray(payload.data)) {
      payload.data = payload.data.map((conversation) => ({
        ...conversation,
        // Employee ids are UUIDs generated by the E2E seed. Normalize only
        // this visual fixture so avatar pixels do not vary between runs.
        entry_employee_id: "e2e-avatar",
      }));
    }
    await route.fulfill({ response, json: payload });
  });
}

async function openChat(
  page: import("@playwright/test").Page,
  request: import("@playwright/test").APIRequestContext,
): Promise<{ id: string; title: string }> {
  const id = `astryx-chat-${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const conversation = { id, title: "Astryx 设计评审" };
  const response = await request.post("/api/agent/conversations", {
    data: {
      id: conversation.id,
      title: conversation.title,
      kind: "private",
      ...((process.env.E2E_AGENT_EMPLOYEE_ID ?? seededEmployeeId()) ? { entry_employee_id: process.env.E2E_AGENT_EMPLOYEE_ID ?? seededEmployeeId() } : {}),
    },
  });
  expect(response.status()).toBe(201);
  await page.goto("/chat");
  await page.getByTestId(`conversation-${conversation.id}`).click();
  await expect(page.getByRole("log", { name: "对话事件流" })).toBeVisible();
  await expect(page.getByRole("textbox", { name: "消息内容" })).toBeVisible();
  return conversation;
}

authTest.describe("Agent Astryx Chat", () => {
  authTest("light mode passes visual, accessibility, keyboard, and console gates", async ({ authedPage, authedRequest }) => {
    const browserErrors = collectBrowserErrors(authedPage);
    await authedPage.emulateMedia({ colorScheme: "light", reducedMotion: "no-preference" });
    await stabilizeConversationAvatars(authedPage);
    await openChat(authedPage, authedRequest);
    // External deployments may contain prior conversations; keep visual snapshots deterministic in local seeded runs.
    if (process.env.E2E_EXTERNAL !== "true") {
      // Wait for the empty event state before capturing the visual baseline; the
      // composer and file panel are otherwise ready before TimelineView finishes
      // its first local entries request.
      await expect(authedPage.getByTestId("conversation-events")).toContainText("暂无事件");
      await expect(authedPage).toHaveScreenshot("agent-chat-light.png", {
        fullPage: true,
        // The empty-state font can differ by a handful of antialiased pixels
        // between Chromium retries; keep the visual gate focused on layout.
        maxDiffPixels: 500,
      });
    }
    const results = await new AxeBuilder({ page: authedPage }).analyze();
    expect(results.violations.filter((item) => item.impact === "critical" || item.impact === "serious")).toEqual([]);
    await expectKeyboardFocusVisible(authedPage);
    expect(browserErrors).toEqual([]);
  });

  authTest("dark and reduced-motion modes remain usable", async ({ authedPage, authedRequest }) => {
    const browserErrors = collectBrowserErrors(authedPage);
    await authedPage.emulateMedia({ colorScheme: "dark", reducedMotion: "reduce" });
    await openChat(authedPage, authedRequest);
    await expect(authedPage.getByRole("textbox", { name: "消息内容" })).toBeEditable();
    await authedPage.getByRole("link", { name: "工作台" }).focus();
    await expect(authedPage.getByRole("link", { name: "工作台" })).toBeFocused();
    expect(browserErrors).toEqual([]);
  });

  authTest("sending a prompt reaches the Node Agent prompt endpoint", async ({ authedPage, authedRequest }) => {
    const conversation = await openChat(authedPage, authedRequest);
    const promptResponse = authedPage.waitForResponse((response) =>
      response.request().method() === "POST" && response.url().endsWith(`/conversations/${conversation.id}/prompt`),
    );
    const textbox = authedPage.getByRole("textbox", { name: "消息内容" });
    await textbox.fill("验证 Astryx 发送主链");
    await authedPage.getByRole("button", { name: "发送" }).click();
    expect((await promptResponse).status()).toBe(202);
    await expect(textbox).toHaveText("");
  });
});
